version: "3"

services:
  app:
    build: .
      container_name: bot
      command: python app.py
      volumes:
        - ./:/app
      env_file:
        .env
    environment: 
      - MONGODB_URL=mongodb://localhost:27017/		
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - mongodb:/db
